In [1]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import pandas as pd
import numpy as np

In [2]:
# instance for sentimental analyzation
sentimental_analyzer = SentimentIntensityAnalyzer()

In [3]:
instagram_information = pd.read_csv('tabllm-batch-generate-65c7a1cb0c70a4ebdc0f4bef-data.csv')
instagram_information

,user number,Start Date,End Date,Instagram Handle (3),Name (4),Number of Pictures (1),Stories Posted (2),Descriptions (3),Captions (4),Hastags (1),Number of Tags by You (2),Number of Tags to You (3),Comments on Others (4),Comments on post (1),Followers (2),Following (3),Interactions with Friends (4),Close Friends (1),Interactions with Close Friends (2)
0,4,2023-09-01,2023-09-30,fashionista23,Sophie Johnson,30,6,"Runway fashion show, Street style photoshoot, ...","Strutting the catwalk, Urban chic, Closet must...","fashion, style, vintage, sustainable, evening","michael, olivia, lucas, emily, nathan","chloe, ethan, lily, josh, sophia","You're a fashion icon! Stunning looks, Love yo...","Gorgeous outfits, Stunning styles, Fashion goals",5897,4856,97,45,88
1,5,2023-10-15,2023-11-10,wellnesswarrior,Zara Khan,18,4,"Morning yoga routine, Healthy meal prep, Sunse...","Mindful mornings, Nutritious meals, Serene eve...","wellness, mindfulness, nutrition, meditation, ...","noah, mia, logan, harper, ethan","sophie, max, emily, lucas, chloe","You inspire us! Healthy living goals, Love you...","Great content, Lovely posts, Wellness goals",7321,8123,82,38,97
2,6,2023-11-20,2023-12-15,musiclover88,Levi Jackson,22,5,"Concert night excitement, Vinyl record collect...","Rocking the stage, Vintage tunes, Creative mel...","music, concerts, vinyl, songwriting, acoustic","ava, noah, chloe, ethan, lily","sophie, logan, emily, lucas, mia","Your music is amazing! Rock on, Love your song...","Great music, Lovely tunes, Awesome performances",8945,5321,90,42,101
3,1,2024-01-01,2024-01-30,adventurous_soul,Elena Rodriguez,25,7,"Hiking in the mountains, Camping under the sta...","Embracing nature's wonders, Sleeping under the...","nature, adventure, camping, hiking, wildlife","lucas, emily, noah, sophia, ethan","mia, josh, chloe, olivia, logan",Your adventures are inspiring! Beautiful captu...,"Gorgeous shots, Stunning views, Nature goals",6754,7983,86,32,92
4,2,2024-02-12,2024-03-10,gourmet_affair,Oscar Martinez,20,5,"Exotic culinary delights, Gourmet food tasting...","Indulging in gastronomic wonders, Savoring uni...","foodie, gourmet, cooking, culinary, dessert","olivia, ethan, mia, lucas, emily","logan, chloe, noah, sophia, josh",Your food journey is amazing! Culinary delight...,"Delicious treats, Gourmet goals, Amazing flavors",5217,6543,75,28,81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,45,2034-08-10,2034-09-05,vintage_vibes,Peyton Kim,40,3,"Retro fashion, Vintage decor, Classic cars","Vintage decor, Classic cars, Retro fashion","vintage, retro, fashion, decor, classic cars","sophia, logan, emily, josh, chloe, olivia, eth...","sophia, logan, emily, josh, chloe, olivia, eth...",Your vintage lifestyle is captivating! Classic...,"Classic cars, Vintage decor, Retro fashion",17500,152000,1750,583,1720
94,46,2034-09-10,2034-10-05,traveling_foodie,Aria Smith,48,9,"Culinary adventures, Exotic cuisines, Food pho...","Exotic cuisines, Food photography, Local delic...","foodie, travel, culinary, food photography, lo...","sophia, logan, emily, josh, chloe, olivia, eth...","sophia, logan, emily, josh, chloe, olivia, eth...",Your culinary journey is inspiring! Food photo...,"Culinary adventures, Exotic cuisines, Local de...",18000,156000,1800,600,1760
95,47,2034-10-10,2034-11-05,fitness_fanatic,Eliana Johnson,47,8,"Workout routines, Fitness motivation, Healthy ...","Fitness motivation, Healthy lifestyle, Strengt...","fitness, workout, healthy, strength training, ...","sophia, logan, emily, josh, chloe, olivia, eth...","sophia, logan, emily, josh, chloe, olivia, eth...",Your fitness journey is inspiring! Cardio exer...,"Workout routines, Strength training, Athletic ...",18500,160000,1850,617,1800
96,48,2034-11-10,2034-12-05,pet_lover,Zara Martinez,46,7,"Adorable pets, Pet adoption, Animal welfare, P...","Pet adoption, Animal welfare, Pet care tips, P...","pets, pet adoption, animal welfare, pet care, ...","sophia, logan, emily, josh, chloe, olivia, eth...","sophia, logan, emily, josh, chloe, olivia, eth...",Your love for pets is heartwarming! Animal wel...,"Pet adoption, Pet care tips, Adorable pets",19000,164000,1900,633,1840
97,49,2034-12-10,2035-01-05,art_enthusiast,Nova Thompson,45,6,"Artistic creations, Creative expressions, Visu...","Creative expressions, Visual arts, Art history...","art, creations, visual arts, history, exhibiti...","sophia, logan, emily, josh, chloe, olivia, eth...","sophia, logan, emily, josh, chloe, olivia, eth...",Your artistic creations are captivating! Art h...,"Creative expressions, Artistic inspirations",19500,168000,1950,650,1880

In [4]:
# get the csv file
comments_and_concerns = pd.read_csv('tabllm-batch-generate-65c7a34a26a4106ff86bde30-data.csv')
comments_and_concerns = comments_and_concerns.drop(columns=['comment_id', 'user_id', 'sentiment'])
comments_and_concerns

                                          comment_text
0           I'm genuinely happy for you! Keep shining!
1    This is utterly disappointing. You should impr...
2                 Sending you love and support always!
3                  This is beyond amazing! Keep it up!
4               You're such a disappointment. Grow up.
..                                                 ...
495  I can't believe how mean people can be sometimes.
496  Your unwavering support means the world. Keep ...
497  This is just devastating. I feel so sad for them.
498  Your infectious laughter and joy brighten up a...
499  You are so mean-spirited and hurtful. Why do y...

[500 rows x 1 columns]

In [5]:
# drop the id column
instagram_information = instagram_information.drop(columns='user number')
instagram_information

,Start Date,End Date,Instagram Handle (3),Name (4),Number of Pictures (1),Stories Posted (2),Descriptions (3),Captions (4),Hastags (1),Number of Tags by You (2),Number of Tags to You (3),Comments on Others (4),Comments on post (1),Followers (2),Following (3),Interactions with Friends (4),Close Friends (1),Interactions with Close Friends (2)
0,2023-09-01,2023-09-30,fashionista23,Sophie Johnson,30,6,"Runway fashion show, Street style photoshoot, ...","Strutting the catwalk, Urban chic, Closet must...","fashion, style, vintage, sustainable, evening","michael, olivia, lucas, emily, nathan","chloe, ethan, lily, josh, sophia","You're a fashion icon! Stunning looks, Love yo...","Gorgeous outfits, Stunning styles, Fashion goals",5897,4856,97,45,88
1,2023-10-15,2023-11-10,wellnesswarrior,Zara Khan,18,4,"Morning yoga routine, Healthy meal prep, Sunse...","Mindful mornings, Nutritious meals, Serene eve...","wellness, mindfulness, nutrition, meditation, ...","noah, mia, logan, harper, ethan","sophie, max, emily, lucas, chloe","You inspire us! Healthy living goals, Love you...","Great content, Lovely posts, Wellness goals",7321,8123,82,38,97
2,2023-11-20,2023-12-15,musiclover88,Levi Jackson,22,5,"Concert night excitement, Vinyl record collect...","Rocking the stage, Vintage tunes, Creative mel...","music, concerts, vinyl, songwriting, acoustic","ava, noah, chloe, ethan, lily","sophie, logan, emily, lucas, mia","Your music is amazing! Rock on, Love your song...","Great music, Lovely tunes, Awesome performances",8945,5321,90,42,101
3,2024-01-01,2024-01-30,adventurous_soul,Elena Rodriguez,25,7,"Hiking in the mountains, Camping under the sta...","Embracing nature's wonders, Sleeping under the...","nature, adventure, camping, hiking, wildlife","lucas, emily, noah, sophia, ethan","mia, josh, chloe, olivia, logan",Your adventures are inspiring! Beautiful captu...,"Gorgeous shots, Stunning views, Nature goals",6754,7983,86,32,92
4,2024-02-12,2024-03-10,gourmet_affair,Oscar Martinez,20,5,"Exotic culinary delights, Gourmet food tasting...","Indulging in gastronomic wonders, Savoring uni...","foodie, gourmet, cooking, culinary, dessert","olivia, ethan, mia, lucas, emily","logan, chloe, noah, sophia, josh",Your food journey is amazing! Culinary delight...,"Delicious treats, Gourmet goals, Amazing flavors",5217,6543,75,28,81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,2034-08-10,2034-09-05,vintage_vibes,Peyton Kim,40,3,"Retro fashion, Vintage decor, Classic cars","Vintage decor, Classic cars, Retro fashion","vintage, retro, fashion, decor, classic cars","sophia, logan, emily, josh, chloe, olivia, eth...","sophia, logan, emily, josh, chloe, olivia, eth...",Your vintage lifestyle is captivating! Classic...,"Classic cars, Vintage decor, Retro fashion",17500,152000,1750,583,1720
94,2034-09-10,2034-10-05,traveling_foodie,Aria Smith,48,9,"Culinary adventures, Exotic cuisines, Food pho...","Exotic cuisines, Food photography, Local delic...","foodie, travel, culinary, food photography, lo...","sophia, logan, emily, josh, chloe, olivia, eth...","sophia, logan, emily, josh, chloe, olivia, eth...",Your culinary journey is inspiring! Food photo...,"Culinary adventures, Exotic cuisines, Local de...",18000,156000,1800,600,1760
95,2034-10-10,2034-11-05,fitness_fanatic,Eliana Johnson,47,8,"Workout routines, Fitness motivation, Healthy ...","Fitness motivation, Healthy lifestyle, Strengt...","fitness, workout, healthy, strength training, ...","sophia, logan, emily, josh, chloe, olivia, eth...","sophia, logan, emily, josh, chloe, olivia, eth...",Your fitness journey is inspiring! Cardio exer...,"Workout routines, Strength training, Athletic ...",18500,160000,1850,617,1800
96,2034-11-10,2034-12-05,pet_lover,Zara Martinez,46,7,"Adorable pets, Pet adoption, Animal welfare, P...","Pet adoption, Animal welfare, Pet care tips, P...","pets, pet adoption, animal welfare, pet care, ...","sophia, logan, emily, josh, chloe, olivia, eth...","sophia, logan, emily, josh, chloe, olivia, eth...",Your love for pets is heartwarming! Animal wel...,"Pet adoption, Pet care tips, Adorable pets",19000,164000,1900,633,1840
97,2034-12-10,2035-01-05,art_enthusiast,Nova Thompson,45,6,"Artistic creations, Creative expressions, Visu...","Creative expressions, Visual arts, Art history...","art, creations, visual arts, history, exhibiti...","sophia, logan, emily, josh, chloe, olivia, eth...","sophia, logan, emily, josh, chloe, olivia, eth...",Your artistic creations are captivating! Art h...,"Creative expressions, Artistic inspirations",19500,168000,1950,650,1880

In [6]:
instagram_information['Number of Tags by You (2)'] = instagram_information['Number of Tags by You (2)'].apply(len)
instagram_information['Number of Tags to You (3)'] = instagram_information['Number of Tags to You (3)'].apply(len)#

In [7]:
num_comments_per_row_col1 = np.random.randint(1, 10, size=len(instagram_information))  # Generate between 1 and 3 comments for column 1
num_comments_per_row_col2 = np.random.randint(1, 10, size=len(instagram_information))  # Generate between 1 and 3 comments for column 2

In [8]:
comments_per_row_col1 = []
comments_per_row_col2 = []
polarity_scores_per_row_col1 = []
polarity_scores_per_row_col2 = []

In [9]:
for num_comments_col1, num_comments_col2 in zip(num_comments_per_row_col1, num_comments_per_row_col2):
    random_indices_col1 = np.random.choice(len(comments_and_concerns), size=num_comments_col1, replace=False)  # Select random comments for column 1
    random_indices_col2 = np.random.choice(len(comments_and_concerns), size=num_comments_col2, replace=False)  # Select random comments for column 2
    comments_col1 = [comments_and_concerns.iloc[random_idx]['comment_text'] for random_idx in random_indices_col1]
    comments_col2 = [comments_and_concerns.iloc[random_idx]['comment_text'] for random_idx in random_indices_col2]
    # Calculate polarity scores for each comment using VADER
    polarity_scores_col1 = [sentimental_analyzer.polarity_scores(comment)['compound'] for comment in comments_col1]
    polarity_scores_col2 = [sentimental_analyzer.polarity_scores(comment)['compound'] for comment in comments_col2]

    comments_per_row_col1.append(comments_col1)
    comments_per_row_col2.append(comments_col2)
    polarity_scores_per_row_col1.append(polarity_scores_col1)
    polarity_scores_per_row_col2.append(polarity_scores_col2)

In [10]:
comments_df_col1 = pd.DataFrame(comments_per_row_col1, columns=[f'Comments_by_you_{i}' for i in range(1, max(num_comments_per_row_col1) + 1)])
comments_df_col1.fillna('None', inplace=True)
comments_df_col1['All Comments by You'] = comments_df_col1.apply(lambda row: [comment if comment != 'None' else 'None' for comment in row], axis=1)

comments_df_col2 = pd.DataFrame(comments_per_row_col2, columns=[f'Comments_to_you_{i}' for i in range(1, max(num_comments_per_row_col2) + 1)])
comments_df_col2.fillna('None', inplace=True)
comments_df_col2['All Comments to You'] = comments_df_col2.apply(lambda row: [comment if comment != 'None' else 'None' for comment in row], axis=1)

In [11]:
# Create DataFrames from the generated polarity scores lists
polarity_scores_df_col1 = pd.DataFrame(polarity_scores_per_row_col1, columns=[f'Polarity_by_you_{i}' for i in range(1, max(num_comments_per_row_col1) + 1)])
polarity_scores_df_col1.fillna(0, inplace=True)
polarity_scores_df_col1['BY_score'] = polarity_scores_df_col1.apply(lambda row: [comment if comment != 0 else 0 for comment in row], axis=1)

polarity_scores_df_col2 = pd.DataFrame(polarity_scores_per_row_col2, columns=[f'Polarity_to_you_{i}' for i in range(1, max(num_comments_per_row_col2) + 1)])
polarity_scores_df_col2.fillna(0, inplace=True)
polarity_scores_df_col2['TO_score'] = polarity_scores_df_col2.apply(lambda row: [comment if comment != 0 else 0 for comment in row], axis=1)

In [12]:
instagram_information = pd.concat([instagram_information, comments_df_col1['All Comments by You'], comments_df_col2['All Comments to You'], polarity_scores_df_col1['BY_score'], polarity_scores_df_col2['TO_score']], axis=1)

In [13]:
# instagram_information['Descriptions (3)'] = instagram_information['Descriptions (3)'].values.tolist()
# instagram_information['Captions (4)'] = instagram_information['Captions (4)'].values.tolist()

In [14]:
instagram_information.drop(columns=['Comments on Others (4)',
       'Comments on post (1)',])

,Start Date,End Date,Instagram Handle (3),Name (4),Number of Pictures (1),Stories Posted (2),Descriptions (3),Captions (4),Hastags (1),Number of Tags by You (2),Number of Tags to You (3),Followers (2),Following (3),Interactions with Friends (4),Close Friends (1),Interactions with Close Friends (2),All Comments by You,All Comments to You,BY_score,TO_score
0,2023-09-01,2023-09-30,fashionista23,Sophie Johnson,30,6,"Runway fashion show, Street style photoshoot, ...","Strutting the catwalk, Urban chic, Closet must...","fashion, style, vintage, sustainable, evening",37,32,5897,4856,97,45,88,"[This is absolutely fantastic! Great job!, You...",[Why are you always so pessimistic? It's drain...,"[0.8707, 0.8516, -0.7774, -0.6962, 0.8221, 0.4...","[-0.5009, 0, 0, 0, 0, 0, 0, 0, 0]"
1,2023-10-15,2023-11-10,wellnesswarrior,Zara Khan,18,4,"Morning yoga routine, Healthy meal prep, Sunse...","Mindful mornings, Nutritious meals, Serene eve...","wellness, mindfulness, nutrition, meditation, ...",31,32,7321,8123,82,38,97,[You have such a warm and loving spirit. Keep ...,"[You're such a disappointment. Grow up., Stop ...","[0.8908, 0.8709, 0.8805, 0.9299, -0.5009, -0.2...","[-0.5106, -0.8268, 0.8268, -0.4767, 0.8908, 0...."
2,2023-11-20,2023-12-15,musiclover88,Levi Jackson,22,5,"Concert night excitement, Vinyl record collect...","Rocking the stage, Vintage tunes, Creative mel...","music, concerts, vinyl, songwriting, acoustic",29,32,8945,5321,90,42,101,"[You're just spreading negativity. Stop., You'...","[Your creativity is truly inspiring!, You're j...","[-0.6705, -0.1027, -0.7548, 0.7177, -0.5719, 0...","[0.8221, 0, 0, 0, 0, 0, 0, 0, 0]"
3,2024-01-01,2024-01-30,adventurous_soul,Elena Rodriguez,25,7,"Hiking in the mountains, Camping under the sta...","Embracing nature's wonders, Sleeping under the...","nature, adventure, camping, hiking, wildlife",33,31,6754,7983,86,32,92,[Your support and encouragement are so uplifti...,[This is truly heartwarming. Keep spreading th...,"[0.6996, -0.7818, -0.5214, 0.4199, 0.7345, -0....","[0.8883, 0.7345, 0.9299, 0.5972, 0.8588, 0.419..."
4,2024-02-12,2024-03-10,gourmet_affair,Oscar Martinez,20,5,"Exotic culinary delights, Gourmet food tasting...","Indulging in gastronomic wonders, Savoring uni...","foodie, gourmet, cooking, culinary, dessert",32,32,5217,6543,75,28,81,[I can't believe how mean people can be someti...,[Your compassion and empathy are truly commend...,"[0, -0.5009, 0.8977, 0.5983, 0.4574, 0.4574, 0...","[0.7345, 0.357, 0.0258, 0, 0.8908, 0, 0, 0, 0]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,2034-08-10,2034-09-05,vintage_vibes,Peyton Kim,40,3,"Retro fashion, Vintage decor, Classic cars","Vintage decor, Classic cars, Retro fashion","vintage, retro, fashion, decor, classic cars",66,66,17500,152000,1750,583,1720,"[This is absolutely fantastic! Great job!, You...",[You're always so negative. Can't you see the ...,"[0.8707, -0.7096, 0, 0.6996, 0.6892, 0, 0, 0, 0]","[-0.4294, -0.6705, 0.6239, 0.8805, 0.4199, 0.8..."
94,2034-09-10,2034-10-05,traveling_foodie,Aria Smith,48,9,"Culinary adventures, Exotic cuisines, Food pho...","Exotic cuisines, Food photography, Local delic...","foodie, travel, culinary, food photography, lo...",66,66,18000,156000,1800,600,1760,[Your creative ideas and innovation are truly ...,[Your encouragement is truly appreciated. Keep...,"[0.8268, 0.8805, -0.6705, 0.8709, 0.8908, -0.6...","[0.8516, 0.4574, -0.7906, -0.296, -0.6962, 0.8..."
95,2034-10-10,2034-11-05,fitness_fanatic,Eliana Johnson,47,8,"Workout routines, Fitness motivation, Healthy ...","Fitness motivation, Healthy lifestyle, Strengt...","fitness, workout, healthy, strength training, ...",66,66,18500,160000,1850,617,1800,"[Your support means everything. Keep shining!,...","[This is really sad. It's disappointing., Your...","[0.4574, -0.8268, 0.8709, 0.8645, 0.8908, -0.6...","[-0.7818, 0.5972, 0.6229, 0.8883, -0.5719, 0.7..."
96,2034-11-10,2034-12-05,pet_lover,Zara Martinez,46,7,"Adorable pets, Pet adoption, Animal welfare, P...","Pet adoption, Animal welfare, Pet care tips, P...","pets, pet adoption, animal welfare, pet care, ...",66,66,19000,164000,1900,633,1840,[You have such a warm and loving spirit. Keep ...,"[This is really sad. It's disappointing., Your...","[0.8908, 0.8977, 0, 0, -0.8516, 0.8516, 0, 0, 0]","[-0.7818, 0.5399, 0.5972, -0.7351, 0, 0.5562, ..."
97,2034-12-10,2035-01-05,art_enthusiast,Nova Thompson,45,6,"Artistic creations, Creative expressions, Visu...","Creative expressions, Visual arts, Art history...","art, creations, visual arts, history, exhibiti...",66,66,19500,168000,1950,650,1880,[I can't believe how mean people can be someti...,[Your support and kindness make a world of dif...,"[0, 0.8805, -0.7506, 0, 0, 0, 0, 0, 0]","[0.7177, 0.5983, 0.8805, 0.9299, -0.5214, 0, 0..."

In [22]:
# Function to calculate sentiment score using VADER
def calculate_sentiment_score(description):
    sentences = description.split(', ')
    sentiment_scores = [sentimental_analyzer.polarity_scores(sentence)['compound'] for sentence in sentences]
    return sentiment_scores

In [23]:
# Apply sentiment analysis function to each description and store scores in a new column
instagram_information['description_score'] = instagram_information['Descriptions (3)'].apply(calculate_sentiment_score)

In [24]:
# Apply sentiment analysis function to each caption and store scores in a new column
instagram_information['caption_Score'] = instagram_information['Captions (4)'].apply(calculate_sentiment_score)

In [25]:
instagram_information

,Start Date,End Date,Instagram Handle (3),Name (4),Number of Pictures (1),Stories Posted (2),Descriptions (3),Captions (4),Hastags (1),Number of Tags by You (2),...,Following (3),Interactions with Friends (4),Close Friends (1),Interactions with Close Friends (2),All Comments by You,All Comments to You,BY_score,TO_score,description_score,caption_Score
0,2023-09-01,2023-09-30,fashionista23,Sophie Johnson,30,6,"Runway fashion show, Street style photoshoot, ...","Strutting the catwalk, Urban chic, Closet must...","fashion, style, vintage, sustainable, evening",37,...,4856,97,45,88,"[This is absolutely fantastic! Great job!, You...",[Why are you always so pessimistic? It's drain...,"[0.8707, 0.8516, -0.7774, -0.6962, 0.8221, 0.4...","[-0.5009, 0, 0, 0, 0, 0, 0, 0, 0]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.5106]","[0.0, 0.2732, 0.0, 0.0, 0.0, 0.5267]"
1,2023-10-15,2023-11-10,wellnesswarrior,Zara Khan,18,4,"Morning yoga routine, Healthy meal prep, Sunse...","Mindful mornings, Nutritious meals, Serene eve...","wellness, mindfulness, nutrition, meditation, ...",31,...,8123,82,38,97,[You have such a warm and loving spirit. Keep ...,"[You're such a disappointment. Grow up., Stop ...","[0.8908, 0.8709, 0.8805, 0.9299, -0.5009, -0.2...","[-0.5106, -0.8268, 0.8268, -0.4767, 0.8908, 0....","[0.0, 0.4019, 0.0, 0.0]","[0.0, 0.0, 0.4588, 0.5719]"
2,2023-11-20,2023-12-15,musiclover88,Levi Jackson,22,5,"Concert night excitement, Vinyl record collect...","Rocking the stage, Vintage tunes, Creative mel...","music, concerts, vinyl, songwriting, acoustic",29,...,5321,90,42,101,"[You're just spreading negativity. Stop., You'...","[Your creativity is truly inspiring!, You're j...","[-0.6705, -0.1027, -0.7548, 0.7177, -0.5719, 0...","[0.8221, 0, 0, 0, 0, 0, 0, 0, 0]","[0.4939, 0.0, 0.0, 0.4939, 0.0]","[0.0, 0.0, 0.4404, 0.4939, 0.0]"
3,2024-01-01,2024-01-30,adventurous_soul,Elena Rodriguez,25,7,"Hiking in the mountains, Camping under the sta...","Embracing nature's wonders, Sleeping under the...","nature, adventure, camping, hiking, wildlife",33,...,7983,86,32,92,[Your support and encouragement are so uplifti...,[This is truly heartwarming. Keep spreading th...,"[0.6996, -0.7818, -0.5214, 0.4199, 0.7345, -0....","[0.8883, 0.7345, 0.9299, 0.5972, 0.8588, 0.419...","[0.0, 0.0, 0.0, 0.34, 0.4588, 0.0, 0.4939]","[0.0, 0.0, 0.4588, 0.0, 0.0, 0.0, 0.4215]"
4,2024-02-12,2024-03-10,gourmet_affair,Oscar Martinez,20,5,"Exotic culinary delights, Gourmet food tasting...","Indulging in gastronomic wonders, Savoring uni...","foodie, gourmet, cooking, culinary, dessert",32,...,6543,75,28,81,[I can't believe how mean people can be someti...,[Your compassion and empathy are truly commend...,"[0, -0.5009, 0.8977, 0.5983, 0.4574, 0.4574, 0...","[0.7345, 0.357, 0.0258, 0, 0.8908, 0, 0, 0, 0]","[0.4588, 0.0, 0.0, 0.0, 0.743]","[0.0, 0.0, 0.0, 0.4588, 0.4588]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,2034-08-10,2034-09-05,vintage_vibes,Peyton Kim,40,3,"Retro fashion, Vintage decor, Classic cars","Vintage decor, Classic cars, Retro fashion","vintage, retro, fashion, decor, classic cars",66,...,152000,1750,583,1720,"[This is absolutely fantastic! Great job!, You...",[You're always so negative. Can't you see the ...,"[0.8707, -0.7096, 0, 0.6996, 0.6892, 0, 0, 0, 0]","[-0.4294, -0.6705, 0.6239, 0.8805, 0.4199, 0.8...","[0.0, 0.0, 0.0]","[0.0, 0.0, 0.0]"
94,2034-09-10,2034-10-05,traveling_foodie,Aria Smith,48,9,"Culinary adventures, Exotic cuisines, Food pho...","Exotic cuisines, Food photography, Local delic...","foodie, travel, culinary, food photography, lo...",66,...,156000,1800,600,1760,[Your creative ideas and innovation are truly ...,[Your encouragement is truly appreciated. Keep...,"[0.8268, 0.8805, -0.6705, 0.8709, 0.8908, -0.6...","[0.8516, 0.4574, -0.7906, -0.296, -0.6962, 0.8...","[0.34, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2023]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2023, 0.34]"
95,2034-10-10,2034-11-05,fitness_fanatic,Eliana Johnson,47,8,"Workout routines, Fitness motivation, Healthy ...","Fitness motivation, Healthy lifestyle, Strengt...","fitness, workout, healthy, strength training, ...",66,...,160000,1850,617,1800,"[Your support means everything. Keep shining!,...","[This is really sad. It's disappointing., Your...","[0.4574, -0.8268, 0.8709, 0.8645, 0.8908, -0.6...","[-0.7818, 0.5972, 0.6229, 0.8883, -0.5719, 0.7...","[0.0, 0.5423, 0.4019, 0.4939, 0.0, 0.0, 0.0, 0.0]","[0.5423, 0.4019, 0.4939, 0.0, 0.0, 0.0, 0.0, 0.0]"
96,2034-11-10,2034-12-05,pet_lover,Zara Martinez,46,7,"Adorable pets, Pet adoption, Animal welfare, P...","Pet adoption, Animal welfare, Pet care tips, P...","pets, pet adoption, animal welfare, pet care, ...",66,...,164000,1900,633,1840,[You have such a warm and loving spirit. Keep ...,"[This is really sad. It's disappointing., Your...","[0.8908, 0.8977, 0, 0, -0.8516, 0.8516, 0, 0, 0]","[-0.7818, 0.5399, 0.5972, -0.7351, 0, 0.5562, ...","[0.4939, 0.0, 0.0, 0.4939, 0.0, 0.4588, 0.4767]","[0.0, 0.0, 0.4939, 0.0, 0.4588, 0.4767, 0.4939]"
97,2034-12-10,2035-01-05,art_enthusiast,Nova Thompson,45,6,"Artistic creations, Creative expressions, Visu...","Creative expressions, Visual arts, Art history...","art, creations, visual arts, history, exhibiti...",66,...,168000,1950,650,1880,[I can't believe how mean people can be someti...,[Your support and kindness make a world of dif...,"[0, 0.8805, -0.7506, 0, 0, 0, 0, 0, 0]","[0.7177, 0.5983, 0.8805, 0.9299, -0.5214, 0, 0...","[0.3818, 0.4404, 0.0, 0.0, 0.0, 0.4767]","[0.4404, 0.0, 0.0, 0.0, 0.4767, 0.3818]"

In [27]:
instagram_information.to_csv('instagram_all.csv')