In [108]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import pandas as pd
import numpy as np

In [109]:
# instance for sentimental analyzation
sentimental_analyzer = SentimentIntensityAnalyzer()

In [110]:
instagram_information = pd.read_csv('datasets/tabllm-batch-generate-65c7a1cb0c70a4ebdc0f4bef-data.csv')
instagram_information

,user number,Start Date,End Date,Instagram Handle (3),Name (4),Number of Pictures (1),Stories Posted (2),Descriptions (3),Captions (4),Hastags (1),Number of Tags by You (2),Number of Tags to You (3),Comments on Others (4),Comments on post (1),Followers (2),Following (3),Interactions with Friends (4),Close Friends (1),Interactions with Close Friends (2)
0,4,2023-09-01,2023-09-30,fashionista23,Sophie Johnson,30,6,"Runway fashion show, Street style photoshoot, ...","Strutting the catwalk, Urban chic, Closet must...","fashion, style, vintage, sustainable, evening","michael, olivia, lucas, emily, nathan","chloe, ethan, lily, josh, sophia","You're a fashion icon! Stunning looks, Love yo...","Gorgeous outfits, Stunning styles, Fashion goals",5897,4856,97,45,88
1,5,2023-10-15,2023-11-10,wellnesswarrior,Zara Khan,18,4,"Morning yoga routine, Healthy meal prep, Sunse...","Mindful mornings, Nutritious meals, Serene eve...","wellness, mindfulness, nutrition, meditation, ...","noah, mia, logan, harper, ethan","sophie, max, emily, lucas, chloe","You inspire us! Healthy living goals, Love you...","Great content, Lovely posts, Wellness goals",7321,8123,82,38,97
2,6,2023-11-20,2023-12-15,musiclover88,Levi Jackson,22,5,"Concert night excitement, Vinyl record collect...","Rocking the stage, Vintage tunes, Creative mel...","music, concerts, vinyl, songwriting, acoustic","ava, noah, chloe, ethan, lily","sophie, logan, emily, lucas, mia","Your music is amazing! Rock on, Love your song...","Great music, Lovely tunes, Awesome performances",8945,5321,90,42,101
3,1,2024-01-01,2024-01-30,adventurous_soul,Elena Rodriguez,25,7,"Hiking in the mountains, Camping under the sta...","Embracing nature's wonders, Sleeping under the...","nature, adventure, camping, hiking, wildlife","lucas, emily, noah, sophia, ethan","mia, josh, chloe, olivia, logan",Your adventures are inspiring! Beautiful captu...,"Gorgeous shots, Stunning views, Nature goals",6754,7983,86,32,92
4,2,2024-02-12,2024-03-10,gourmet_affair,Oscar Martinez,20,5,"Exotic culinary delights, Gourmet food tasting...","Indulging in gastronomic wonders, Savoring uni...","foodie, gourmet, cooking, culinary, dessert","olivia, ethan, mia, lucas, emily","logan, chloe, noah, sophia, josh",Your food journey is amazing! Culinary delight...,"Delicious treats, Gourmet goals, Amazing flavors",5217,6543,75,28,81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,45,2034-08-10,2034-09-05,vintage_vibes,Peyton Kim,40,3,"Retro fashion, Vintage decor, Classic cars","Vintage decor, Classic cars, Retro fashion","vintage, retro, fashion, decor, classic cars","sophia, logan, emily, josh, chloe, olivia, eth...","sophia, logan, emily, josh, chloe, olivia, eth...",Your vintage lifestyle is captivating! Classic...,"Classic cars, Vintage decor, Retro fashion",17500,152000,1750,583,1720
94,46,2034-09-10,2034-10-05,traveling_foodie,Aria Smith,48,9,"Culinary adventures, Exotic cuisines, Food pho...","Exotic cuisines, Food photography, Local delic...","foodie, travel, culinary, food photography, lo...","sophia, logan, emily, josh, chloe, olivia, eth...","sophia, logan, emily, josh, chloe, olivia, eth...",Your culinary journey is inspiring! Food photo...,"Culinary adventures, Exotic cuisines, Local de...",18000,156000,1800,600,1760
95,47,2034-10-10,2034-11-05,fitness_fanatic,Eliana Johnson,47,8,"Workout routines, Fitness motivation, Healthy ...","Fitness motivation, Healthy lifestyle, Strengt...","fitness, workout, healthy, strength training, ...","sophia, logan, emily, josh, chloe, olivia, eth...","sophia, logan, emily, josh, chloe, olivia, eth...",Your fitness journey is inspiring! Cardio exer...,"Workout routines, Strength training, Athletic ...",18500,160000,1850,617,1800
96,48,2034-11-10,2034-12-05,pet_lover,Zara Martinez,46,7,"Adorable pets, Pet adoption, Animal welfare, P...","Pet adoption, Animal welfare, Pet care tips, P...","pets, pet adoption, animal welfare, pet care, ...","sophia, logan, emily, josh, chloe, olivia, eth...","sophia, logan, emily, josh, chloe, olivia, eth...",Your love for pets is heartwarming! Animal wel...,"Pet adoption, Pet care tips, Adorable pets",19000,164000,1900,633,1840
97,49,2034-12-10,2035-01-05,art_enthusiast,Nova Thompson,45,6,"Artistic creations, Creative expressions, Visu...","Creative expressions, Visual arts, Art history...","art, creations, visual arts, history, exhibiti...","sophia, logan, emily, josh, chloe, olivia, eth...","sophia, logan, emily, josh, chloe, olivia, eth...",Your artistic creations are captivating! Art h...,"Creative expressions, Artistic inspirations",19500,168000,1950,650,1880

In [111]:
# get the csv file
comments_and_concerns = pd.read_csv('datasets/comment_db.csv')
# comments_and_concerns = comments_and_concerns.drop(columns=['user_id', 'sentiment'])
comments_and_concerns

                                              comments   emotion
0               Excited to start a new chapter in life     happy
1                  Feeling heartbroken after a breakup       sad
2                   Angry at the constant traffic jams     angry
3                     Proud of my child's achievements     proud
4    Disgusted by the lack of hygiene in public places   disgust
..                                                 ...       ...
995     Seeking tranquility in the midst of a busy day  calmness
996           Excited about a new personal achievement     happy
997                  Touched by a heartwarming gesture       sad
998  Angry at the lack of support for mental health...     angry
999  Proud of the progress made in overcoming perso...     proud

[1000 rows x 2 columns]

In [112]:
# drop the id column
instagram_information = instagram_information.drop(columns='user number')
instagram_information

,Start Date,End Date,Instagram Handle (3),Name (4),Number of Pictures (1),Stories Posted (2),Descriptions (3),Captions (4),Hastags (1),Number of Tags by You (2),Number of Tags to You (3),Comments on Others (4),Comments on post (1),Followers (2),Following (3),Interactions with Friends (4),Close Friends (1),Interactions with Close Friends (2)
0,2023-09-01,2023-09-30,fashionista23,Sophie Johnson,30,6,"Runway fashion show, Street style photoshoot, ...","Strutting the catwalk, Urban chic, Closet must...","fashion, style, vintage, sustainable, evening","michael, olivia, lucas, emily, nathan","chloe, ethan, lily, josh, sophia","You're a fashion icon! Stunning looks, Love yo...","Gorgeous outfits, Stunning styles, Fashion goals",5897,4856,97,45,88
1,2023-10-15,2023-11-10,wellnesswarrior,Zara Khan,18,4,"Morning yoga routine, Healthy meal prep, Sunse...","Mindful mornings, Nutritious meals, Serene eve...","wellness, mindfulness, nutrition, meditation, ...","noah, mia, logan, harper, ethan","sophie, max, emily, lucas, chloe","You inspire us! Healthy living goals, Love you...","Great content, Lovely posts, Wellness goals",7321,8123,82,38,97
2,2023-11-20,2023-12-15,musiclover88,Levi Jackson,22,5,"Concert night excitement, Vinyl record collect...","Rocking the stage, Vintage tunes, Creative mel...","music, concerts, vinyl, songwriting, acoustic","ava, noah, chloe, ethan, lily","sophie, logan, emily, lucas, mia","Your music is amazing! Rock on, Love your song...","Great music, Lovely tunes, Awesome performances",8945,5321,90,42,101
3,2024-01-01,2024-01-30,adventurous_soul,Elena Rodriguez,25,7,"Hiking in the mountains, Camping under the sta...","Embracing nature's wonders, Sleeping under the...","nature, adventure, camping, hiking, wildlife","lucas, emily, noah, sophia, ethan","mia, josh, chloe, olivia, logan",Your adventures are inspiring! Beautiful captu...,"Gorgeous shots, Stunning views, Nature goals",6754,7983,86,32,92
4,2024-02-12,2024-03-10,gourmet_affair,Oscar Martinez,20,5,"Exotic culinary delights, Gourmet food tasting...","Indulging in gastronomic wonders, Savoring uni...","foodie, gourmet, cooking, culinary, dessert","olivia, ethan, mia, lucas, emily","logan, chloe, noah, sophia, josh",Your food journey is amazing! Culinary delight...,"Delicious treats, Gourmet goals, Amazing flavors",5217,6543,75,28,81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,2034-08-10,2034-09-05,vintage_vibes,Peyton Kim,40,3,"Retro fashion, Vintage decor, Classic cars","Vintage decor, Classic cars, Retro fashion","vintage, retro, fashion, decor, classic cars","sophia, logan, emily, josh, chloe, olivia, eth...","sophia, logan, emily, josh, chloe, olivia, eth...",Your vintage lifestyle is captivating! Classic...,"Classic cars, Vintage decor, Retro fashion",17500,152000,1750,583,1720
94,2034-09-10,2034-10-05,traveling_foodie,Aria Smith,48,9,"Culinary adventures, Exotic cuisines, Food pho...","Exotic cuisines, Food photography, Local delic...","foodie, travel, culinary, food photography, lo...","sophia, logan, emily, josh, chloe, olivia, eth...","sophia, logan, emily, josh, chloe, olivia, eth...",Your culinary journey is inspiring! Food photo...,"Culinary adventures, Exotic cuisines, Local de...",18000,156000,1800,600,1760
95,2034-10-10,2034-11-05,fitness_fanatic,Eliana Johnson,47,8,"Workout routines, Fitness motivation, Healthy ...","Fitness motivation, Healthy lifestyle, Strengt...","fitness, workout, healthy, strength training, ...","sophia, logan, emily, josh, chloe, olivia, eth...","sophia, logan, emily, josh, chloe, olivia, eth...",Your fitness journey is inspiring! Cardio exer...,"Workout routines, Strength training, Athletic ...",18500,160000,1850,617,1800
96,2034-11-10,2034-12-05,pet_lover,Zara Martinez,46,7,"Adorable pets, Pet adoption, Animal welfare, P...","Pet adoption, Animal welfare, Pet care tips, P...","pets, pet adoption, animal welfare, pet care, ...","sophia, logan, emily, josh, chloe, olivia, eth...","sophia, logan, emily, josh, chloe, olivia, eth...",Your love for pets is heartwarming! Animal wel...,"Pet adoption, Pet care tips, Adorable pets",19000,164000,1900,633,1840
97,2034-12-10,2035-01-05,art_enthusiast,Nova Thompson,45,6,"Artistic creations, Creative expressions, Visu...","Creative expressions, Visual arts, Art history...","art, creations, visual arts, history, exhibiti...","sophia, logan, emily, josh, chloe, olivia, eth...","sophia, logan, emily, josh, chloe, olivia, eth...",Your artistic creations are captivating! Art h...,"Creative expressions, Artistic inspirations",19500,168000,1950,650,1880

In [113]:
instagram_information['Number of Tags by You (2)'] = instagram_information['Number of Tags by You (2)'].apply(len)
instagram_information['Number of Tags to You (3)'] = instagram_information['Number of Tags to You (3)'].apply(len)#

In [114]:
num_comments_per_row_col1 = np.random.randint(1, 10, size=len(instagram_information))  # Generate between 1 and 3 comments for column 1
num_comments_per_row_col2 = np.random.randint(1, 10, size=len(instagram_information))  # Generate between 1 and 3 comments for column 2

In [115]:
comments_per_row_col1 = []
comments_per_row_col2 = []
polarity_scores_per_row_col1 = []
polarity_scores_per_row_col2 = []

In [116]:
for num_comments_col1, num_comments_col2 in zip(num_comments_per_row_col1, num_comments_per_row_col2):
    random_indices_col1 = np.random.choice(len(comments_and_concerns), size=num_comments_col1, replace=False)  # Select random comments for column 1
    random_indices_col2 = np.random.choice(len(comments_and_concerns), size=num_comments_col2, replace=False)  # Select random comments for column 2
    comments_col1 = [comments_and_concerns.iloc[random_idx]['comments'] for random_idx in random_indices_col1]
    comments_col2 = [comments_and_concerns.iloc[random_idx]['comments'] for random_idx in random_indices_col2]
    # Calculate polarity scores for each comment using VADER
    polarity_scores_col1 = [sentimental_analyzer.polarity_scores(comment)['compound'] for comment in comments_col1]
    polarity_scores_col2 = [sentimental_analyzer.polarity_scores(comment)['compound'] for comment in comments_col2]

    comments_per_row_col1.append(comments_col1)
    comments_per_row_col2.append(comments_col2)
    polarity_scores_per_row_col1.append(polarity_scores_col1)
    polarity_scores_per_row_col2.append(polarity_scores_col2)

In [117]:
comments_df_col1 = pd.DataFrame(comments_per_row_col1, columns=[f'Comments_by_you_{i}' for i in range(1, max(num_comments_per_row_col1) + 1)])
comments_df_col1.fillna('None', inplace=True)
comments_df_col1['All Comments by You'] = comments_df_col1.apply(lambda row: [comment if comment != 'None' else 'None' for comment in row], axis=1)

comments_df_col2 = pd.DataFrame(comments_per_row_col2, columns=[f'Comments_to_you_{i}' for i in range(1, max(num_comments_per_row_col2) + 1)])
comments_df_col2.fillna('None', inplace=True)
comments_df_col2['All Comments to You'] = comments_df_col2.apply(lambda row: [comment if comment != 'None' else 'None' for comment in row], axis=1)

In [118]:
# Create DataFrames from the generated polarity scores lists
polarity_scores_df_col1 = pd.DataFrame(polarity_scores_per_row_col1, columns=[f'Polarity_by_you_{i}' for i in range(1, max(num_comments_per_row_col1) + 1)])
polarity_scores_df_col1.fillna(0, inplace=True)
polarity_scores_df_col1['BY_score'] = polarity_scores_df_col1.apply(lambda row: [comment if comment != 0 else 0 for comment in row], axis=1)

polarity_scores_df_col2 = pd.DataFrame(polarity_scores_per_row_col2, columns=[f'Polarity_to_you_{i}' for i in range(1, max(num_comments_per_row_col2) + 1)])
polarity_scores_df_col2.fillna(0, inplace=True)
polarity_scores_df_col2['TO_score'] = polarity_scores_df_col2.apply(lambda row: [comment if comment != 0 else 0 for comment in row], axis=1)

In [119]:
instagram_information = pd.concat([instagram_information, comments_df_col1['All Comments by You'], comments_df_col2['All Comments to You'], polarity_scores_df_col1['BY_score'], polarity_scores_df_col2['TO_score']], axis=1)

In [120]:
# Function to calculate sentiment score using VADER
def calculate_sentiment_score(description):
    sentences = description.split(', ')
    sentiment_scores = [sentimental_analyzer.polarity_scores(sentence)['compound'] for sentence in sentences]
    return sentiment_scores

In [121]:
# Apply sentiment analysis function to each description and store scores in a new column
instagram_information['description_score'] = instagram_information['Descriptions (3)'].apply(calculate_sentiment_score)

In [122]:
# Apply sentiment analysis function to each caption and store scores in a new column
instagram_information['caption_Score'] = instagram_information['Captions (4)'].apply(calculate_sentiment_score)

In [123]:
instagram_information.drop(columns=['Comments on Others (4)',
       'Comments on post (1)',])
instagram_information['story_views'] = np.random.randint(0, 12000, size=len(instagram_information))
instagram_information['hours_spent'] = np.random.randint(0, 15, size=len(instagram_information))
instagram_information

,Start Date,End Date,Instagram Handle (3),Name (4),Number of Pictures (1),Stories Posted (2),Descriptions (3),Captions (4),Hastags (1),Number of Tags by You (2),...,Close Friends (1),Interactions with Close Friends (2),All Comments by You,All Comments to You,BY_score,TO_score,description_score,caption_Score,story_views,hours_spent
0,2023-09-01,2023-09-30,fashionista23,Sophie Johnson,30,6,"Runway fashion show, Street style photoshoot, ...","Strutting the catwalk, Urban chic, Closet must...","fashion, style, vintage, sustainable, evening",37,...,45,88,"[Amused by the antics of a playful puppy, Appa...",[Appalled by the lack of access to education f...,"[0.6908, -0.296, 0, 0, 0, 0, 0, 0, 0]","[-0.6486, -0.1027, -0.2263, 0.34, 0.7906, 0.45...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.5106]","[0.0, 0.2732, 0.0, 0.0, 0.0, 0.5267]",1935,14
1,2023-10-15,2023-11-10,wellnesswarrior,Zara Khan,18,4,"Morning yoga routine, Healthy meal prep, Sunse...","Mindful mornings, Nutritious meals, Serene eve...","wellness, mindfulness, nutrition, meditation, ...",31,...,38,97,[Angry at the lack of support for mental healt...,[Angry at the lack of support for mental healt...,"[-0.4404, -0.1027, 0.8591, 0.8176, 0.4767, 0.4...","[-0.4404, 0.4767, 0.7096, 0.8591, 0.5423, 0.58...","[0.0, 0.4019, 0.0, 0.0]","[0.0, 0.0, 0.4588, 0.5719]",6370,11
2,2023-11-20,2023-12-15,musiclover88,Levi Jackson,22,5,"Concert night excitement, Vinyl record collect...","Rocking the stage, Vintage tunes, Creative mel...","music, concerts, vinyl, songwriting, acoustic",29,...,42,101,"[Embracing the serenity of a starry night, App...",[Surprised by an unexpected encounter with wil...,"[0, -0.6486, 0.5719, -0.7184, 0.7351, -0.7184,...","[0.2263, 0.6249, 0.4767, 0.5423, 0.5859, 0, 0,...","[0.4939, 0.0, 0.0, 0.4939, 0.0]","[0.0, 0.0, 0.4404, 0.4939, 0.0]",3209,8
3,2024-01-01,2024-01-30,adventurous_soul,Elena Rodriguez,25,7,"Hiking in the mountains, Camping under the sta...","Embracing nature's wonders, Sleeping under the...","nature, adventure, camping, hiking, wildlife",33,...,32,92,[Furious about the lack of action on climate c...,"[Disgusted by the lack of empathy in society, ...","[-0.7184, 0.5719, 0, 0, 0, 0, 0, 0, 0]","[-0.6908, 0.7906, 0.7184, -0.836, 0.7351, 0.05...","[0.0, 0.0, 0.0, 0.34, 0.4588, 0.0, 0.4939]","[0.0, 0.0, 0.4588, 0.0, 0.0, 0.0, 0.4215]",1448,1
4,2024-02-12,2024-03-10,gourmet_affair,Oscar Martinez,20,5,"Exotic culinary delights, Gourmet food tasting...","Indulging in gastronomic wonders, Savoring uni...","foodie, gourmet, cooking, culinary, dessert",32,...,28,81,[Embracing the peace and quiet of a relaxing v...,[Angry at the lack of support for mental healt...,"[0.7717, -0.6705, 0, 0, 0, 0, 0, 0, 0]","[-0.4404, 0.6369, 0.5423, 0, 0, 0, 0, 0, 0]","[0.4588, 0.0, 0.0, 0.0, 0.743]","[0.0, 0.0, 0.0, 0.4588, 0.4588]",6518,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,2034-08-10,2034-09-05,vintage_vibes,Peyton Kim,40,3,"Retro fashion, Vintage decor, Classic cars","Vintage decor, Classic cars, Retro fashion","vintage, retro, fashion, decor, classic cars",66,...,583,1720,"[Feeling a sense of longing for a lost pet, Fi...","[Proud of the achievements of a family member,...","[-0.2263, 0.5423, 0.6369, -0.7184, 0.4404, -0....","[0.4767, -0.34, 0.5859, 0.4404, 0.4215, 0.1027...","[0.0, 0.0, 0.0]","[0.0, 0.0, 0.0]",8455,5
94,2034-09-10,2034-10-05,traveling_foodie,Aria Smith,48,9,"Culinary adventures, Exotic cuisines, Food pho...","Exotic cuisines, Food photography, Local delic...","foodie, travel, culinary, food photography, lo...",66,...,600,1760,[Infuriated by the lack of action on gender-ba...,[Touched by a heartwarming act of kindness fro...,"[-0.886, 0.5859, 0.34, 0, 0, 0, 0, 0, 0]","[0.7269, 0, 0, 0, 0, 0, 0, 0, 0]","[0.34, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2023]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2023, 0.34]",3308,10
95,2034-10-10,2034-11-05,fitness_fanatic,Eliana Johnson,47,8,"Workout routines, Fitness motivation, Healthy ...","Fitness motivation, Healthy lifestyle, Strengt...","fitness, workout, healthy, strength training, ...",66,...,617,1800,[Appalled by the lack of access to education f...,"[Finding peace in the midst of a chaotic day, ...","[-0.6486, 0.5423, -0.7184, -0.7184, 0.2263, 0....","[0.0772, 0.7351, -0.836, 0.7906, -0.7184, 0, 0...","[0.0, 0.5423, 0.4019, 0.4939, 0.0, 0.0, 0.0, 0.0]","[0.5423, 0.4019, 0.4939, 0.0, 0.0, 0.0, 0.0, 0.0]",6607,1
96,2034-11-10,2034-12-05,pet_lover,Zara Martinez,46,7,"Adorable pets, Pet adoption, Animal welfare, P...","Pet adoption, Animal welfare, Pet care tips, P...","pets, pet adoption, animal welfare, pet care, ...",66,...,633,1840,[Repulsed by the lack of action on human traff...,[Infuriated by the lack of action on climate c...,"[-0.6705, -0.8481, -0.2263, 0, -0.6597, 0.4767...","[-0.743, -0.6486, 0.5106, 0.7506, 0.4767, 0.79...","[0.4939, 0.0, 0.0, 0.4939, 0.0, 0.4588, 0.4767]","[0.0, 0.0, 0.4939, 0.0, 0.4588, 0.4767, 0.4939]",10298,6
97,2034-12-10,2035-01-05,art_enthusiast,Nova Thompson,45,6,"Artistic creations, Creative expressions, Visu...","Creative expressions, Visual arts, Art history...","art, creations, visual arts, history, exhibiti...",66,...,650,1880,[Appalled by the lack of access to education f...,[Saddened by the destruction caused by natural...,"[-0.6486, -0.34, -0.7906, 0.8591, -0.5423, 0.7...","[-0.8481, 0.7906, 0, -0.4404, 0.25, 0.743, 0.6...","[0.3818, 0.4404, 0.0, 0.0, 0.0, 0.4767]","[0.4404, 0.0, 0.0, 0.0, 0.4767, 0.3818]",8925,11

In [124]:
dict = {'Instagram Handle (3)': 'Instagram_handle',
        'Name (4)': 'Name',
        'Number of Pictures (1)': 'no_of_posts',
        'Stories Posted (2)': 'story_posted',
        'Descriptions (3)': 'picture_description',
        'Captions (4)': 'post_captions',
        'Hastags (1)': 'post_hastags',
        'Number of Tags by You (2)' : 'post_tag_by_you',
        'Number of Tags to You (3)' : 'post_tag_to_you',
        'Followers (2)' : 'your_followers',
        'Following (3)' : 'you_following',
        'Interactions with Friends (4)' : 'interaction_with_your_friends',
        'Close Friends (1)' : 'your_close_friends',
        'Interactions with Close Friends (2)' : 'interaction_with_your_close_friends',
        'All Comments by You' : 'all_comments_by_you',
        'All Comments to You' : 'all_comments_to_you'}

instagram_information = instagram_information.rename(columns=dict)

In [125]:
instagram_information

,Start Date,End Date,Instagram_handle,Name,no_of_posts,story_posted,picture_description,post_captions,post_hastags,post_tag_by_you,...,your_close_friends,interaction_with_your_close_friends,all_comments_by_you,all_comments_to_you,BY_score,TO_score,description_score,caption_Score,story_views,hours_spent
0,2023-09-01,2023-09-30,fashionista23,Sophie Johnson,30,6,"Runway fashion show, Street style photoshoot, ...","Strutting the catwalk, Urban chic, Closet must...","fashion, style, vintage, sustainable, evening",37,...,45,88,"[Amused by the antics of a playful puppy, Appa...",[Appalled by the lack of access to education f...,"[0.6908, -0.296, 0, 0, 0, 0, 0, 0, 0]","[-0.6486, -0.1027, -0.2263, 0.34, 0.7906, 0.45...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.5106]","[0.0, 0.2732, 0.0, 0.0, 0.0, 0.5267]",1935,14
1,2023-10-15,2023-11-10,wellnesswarrior,Zara Khan,18,4,"Morning yoga routine, Healthy meal prep, Sunse...","Mindful mornings, Nutritious meals, Serene eve...","wellness, mindfulness, nutrition, meditation, ...",31,...,38,97,[Angry at the lack of support for mental healt...,[Angry at the lack of support for mental healt...,"[-0.4404, -0.1027, 0.8591, 0.8176, 0.4767, 0.4...","[-0.4404, 0.4767, 0.7096, 0.8591, 0.5423, 0.58...","[0.0, 0.4019, 0.0, 0.0]","[0.0, 0.0, 0.4588, 0.5719]",6370,11
2,2023-11-20,2023-12-15,musiclover88,Levi Jackson,22,5,"Concert night excitement, Vinyl record collect...","Rocking the stage, Vintage tunes, Creative mel...","music, concerts, vinyl, songwriting, acoustic",29,...,42,101,"[Embracing the serenity of a starry night, App...",[Surprised by an unexpected encounter with wil...,"[0, -0.6486, 0.5719, -0.7184, 0.7351, -0.7184,...","[0.2263, 0.6249, 0.4767, 0.5423, 0.5859, 0, 0,...","[0.4939, 0.0, 0.0, 0.4939, 0.0]","[0.0, 0.0, 0.4404, 0.4939, 0.0]",3209,8
3,2024-01-01,2024-01-30,adventurous_soul,Elena Rodriguez,25,7,"Hiking in the mountains, Camping under the sta...","Embracing nature's wonders, Sleeping under the...","nature, adventure, camping, hiking, wildlife",33,...,32,92,[Furious about the lack of action on climate c...,"[Disgusted by the lack of empathy in society, ...","[-0.7184, 0.5719, 0, 0, 0, 0, 0, 0, 0]","[-0.6908, 0.7906, 0.7184, -0.836, 0.7351, 0.05...","[0.0, 0.0, 0.0, 0.34, 0.4588, 0.0, 0.4939]","[0.0, 0.0, 0.4588, 0.0, 0.0, 0.0, 0.4215]",1448,1
4,2024-02-12,2024-03-10,gourmet_affair,Oscar Martinez,20,5,"Exotic culinary delights, Gourmet food tasting...","Indulging in gastronomic wonders, Savoring uni...","foodie, gourmet, cooking, culinary, dessert",32,...,28,81,[Embracing the peace and quiet of a relaxing v...,[Angry at the lack of support for mental healt...,"[0.7717, -0.6705, 0, 0, 0, 0, 0, 0, 0]","[-0.4404, 0.6369, 0.5423, 0, 0, 0, 0, 0, 0]","[0.4588, 0.0, 0.0, 0.0, 0.743]","[0.0, 0.0, 0.0, 0.4588, 0.4588]",6518,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,2034-08-10,2034-09-05,vintage_vibes,Peyton Kim,40,3,"Retro fashion, Vintage decor, Classic cars","Vintage decor, Classic cars, Retro fashion","vintage, retro, fashion, decor, classic cars",66,...,583,1720,"[Feeling a sense of longing for a lost pet, Fi...","[Proud of the achievements of a family member,...","[-0.2263, 0.5423, 0.6369, -0.7184, 0.4404, -0....","[0.4767, -0.34, 0.5859, 0.4404, 0.4215, 0.1027...","[0.0, 0.0, 0.0]","[0.0, 0.0, 0.0]",8455,5
94,2034-09-10,2034-10-05,traveling_foodie,Aria Smith,48,9,"Culinary adventures, Exotic cuisines, Food pho...","Exotic cuisines, Food photography, Local delic...","foodie, travel, culinary, food photography, lo...",66,...,600,1760,[Infuriated by the lack of action on gender-ba...,[Touched by a heartwarming act of kindness fro...,"[-0.886, 0.5859, 0.34, 0, 0, 0, 0, 0, 0]","[0.7269, 0, 0, 0, 0, 0, 0, 0, 0]","[0.34, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2023]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2023, 0.34]",3308,10
95,2034-10-10,2034-11-05,fitness_fanatic,Eliana Johnson,47,8,"Workout routines, Fitness motivation, Healthy ...","Fitness motivation, Healthy lifestyle, Strengt...","fitness, workout, healthy, strength training, ...",66,...,617,1800,[Appalled by the lack of access to education f...,"[Finding peace in the midst of a chaotic day, ...","[-0.6486, 0.5423, -0.7184, -0.7184, 0.2263, 0....","[0.0772, 0.7351, -0.836, 0.7906, -0.7184, 0, 0...","[0.0, 0.5423, 0.4019, 0.4939, 0.0, 0.0, 0.0, 0.0]","[0.5423, 0.4019, 0.4939, 0.0, 0.0, 0.0, 0.0, 0.0]",6607,1
96,2034-11-10,2034-12-05,pet_lover,Zara Martinez,46,7,"Adorable pets, Pet adoption, Animal welfare, P...","Pet adoption, Animal welfare, Pet care tips, P...","pets, pet adoption, animal welfare, pet care, ...",66,...,633,1840,[Repulsed by the lack of action on human traff...,[Infuriated by the lack of action on climate c...,"[-0.6705, -0.8481, -0.2263, 0, -0.6597, 0.4767...","[-0.743, -0.6486, 0.5106, 0.7506, 0.4767, 0.79...","[0.4939, 0.0, 0.0, 0.4939, 0.0, 0.4588, 0.4767]","[0.0, 0.0, 0.4939, 0.0, 0.4588, 0.4767, 0.4939]",10298,6
97,2034-12-10,2035-01-05,art_enthusiast,Nova Thompson,45,6,"Artistic creations, Creative expressions, Visu...","Creative expressions, Visual arts, Art history...","art, creations, visual arts, history, exhibiti...",66,...,650,1880,[Appalled by the lack of access to education f...,[Saddened by the destruction caused by natural...,"[-0.6486, -0.34, -0.7906, 0.8591, -0.5423, 0.7...","[-0.8481, 0.7906, 0, -0.4404, 0.25, 0.743, 0.6...","[0.3818, 0.4404, 0.0, 0.0, 0.0, 0.4767]","[0.4404, 0.0, 0.0, 0.0, 0.4767, 0.3818]",8925,11

In [126]:
instagram_information.to_csv('datasets/instagram_all.csv', mode='w')

In [32]:

from collections import Counter
import re



# Remove brackets and parentheses
instaClean = instagram_information.applymap(lambda x: re.sub(r'[\[\]\(\)"\']', '', str(x)))

# Convert to lowercase
instaClean = instaClean.applymap(lambda x: x.lower())

# Define filler words to remove
filler_words = ['the', 'and', 'is', 'of', 'in', 'to', 'a', 'for', 'on', 'with', 'I','you','your','youre','he','she','we','they','it','its']

# Remove filler words
instaClean = instaClean.applymap(lambda x: ' '.join([word for word in x.split() if word not in filler_words]))



# Group the dataframe by the first column
grouped_df = instaClean.groupby(instaClean.columns[0])


# Iterate over each group
for user, group in grouped_df:
    print(f"User: {user}")
    
    # Concatenate the words for each user
    group['concatenated_words'] = group.apply(lambda row: ' '.join(row[6:8].astype(str)).join(row[11:12].astype(str)).join(row[18:19].astype(str)), axis=1)
    
    # Split the concatenated words into individual words
    words = group['concatenated_words'].str.split()
    
    # Flatten the list of words
    words_flat = [word for sublist in words for word in sublist]
    
    # Count the occurrences of each word
    word_counts = Counter(words_flat)
    
    # Get the 5 most common words
    most_common_words = word_counts.most_common(5)
    
    # Print the most common words for each user
    for word, count in most_common_words:
        print(word, count)
    print()

User: 2023-09-01
this 2
positivity 2
infectious! 2
keep 2
spreading 2

User: 2023-10-15
none, 6
spreading 2
just 1
negativity. 1
stop., 1

User: 2023-11-20
keep 3
stop 2
such 2
being 1
so 1

User: 2024-01-01
so 3
none, 3
always 2
why 2
an 1

User: 2024-02-12
keep 4
truly 3
are 2
up!, 2
positivity!, 2

User: 2024-03-20
none, 7
an 1
incredible 1
human 1
being. 1

User: 2024-04-20
none, 4
keep 2
just 2
it., 2
an 1

User: 2024-05-20
this 4
so 3
disappointing. 2
truly 2
heartwarming. 2

User: 2024-06-20
none, 4
truly 2
keep 2
creative 1
ideas 1

User: 2024-07-20
keep 7
truly 3
support 2
kindness 2
up!, 2

User: 2024-08-20
great 3
this 2
absolutely 2
fantastic! 2
job!, 2

User: 2024-09-20
none, 4
support 3
this 1
so 1
disappointing. 1

User: 2024-10-20
this 2
be 2
keep 2
terrible. 1
should 1

User: 2024-11-20
keep 5
spreading 3
just 3
i 2
this 2

User: 2024-12-20
this 4
so 3
keep 2
just 2
cant 2

User: 2025-01-20
none, 5
this 2
strength 1
resilience 1
are 1

User: 2025-02-20
keep 6
truly 3
kindness 2
up!, 2
spreading 2

User: 2025-03-20
none, 7
just 1
downer. 1
cant 1
stand 1

User: 2025-04-20
keep 4
this 2
making 2
up!, 2
spreading 2

User: 2025-05-20
why 2
do 2
have 2
be 2
so 2

User: 2025-06-20
none, 5
this 2
truly 2
amazing! 2
keep 2

User: 2025-07-20
keep 5
are 4
truly 4
appreciated. 3
why 2

User: 2025-08-20
none, 7
creativity 1
truly 1
inspiring!, 1
none 1

User: 2025-09-20
keep 4
ray 2
sunshine! 2
spreading 2
shining!, 2

User: 2025-10-20
keep 7
truly 3
support 3
means 3
spreading 2

User: 2025-11-20
none, 4
support 3
keep 3
means 2
kindness 1

User: 2025-12-20
none, 7
creativity 1
truly 1
inspiring!, 1
none 1

User: 2026-01-20
truly 3
none, 3
kindness 2
appreciated. 2
keep 2

User: 2026-02-20
none, 4
keep 3
truly 2
appreciated. 2
up!, 2

User: 2026-03-20
this 3
cant 2
really 2
sad. 2
disappointing., 2

User: 2026-04-20
none, 5
positive 1
attitude 1
infectious!, 1
this 1

User: 2026-05-20
this 3
so 2
heartwarming. 2
thank 2
none, 2

User: 2026-06-20
none, 5
keep 2
shining!, 2
content 1
always 1

User: 2026-07-20
none, 5
keep 2
spreading 2
enthusiasm 1
infectious! 1

User: 2026-08-20
keep 5
this 4
truly 4
heartwarming. 4
spreading 4

User: 2026-09-20
keep 3
this 3
none, 3
heartwarming. 2
an 1

User: 2026-10-20
keep 5
are 2
truly 2
just 2
cant 2

User: 2026-11-20
none, 6
positivity 1
needed. 1
keep 1
up!, 1

User: 2026-12-20
none, 4
keep 3
this 2
heartwarming. 2
spreading 2

User: 2027-01-20
none, 7
unwavering 1
support 1
means 1
world. 1

User: 2027-02-20
this 2
great 2
job!, 2
infectious! 2
keep 2

User: 2027-03-20
none, 7
kindness 1
truly 1
appreciated. 1
keep 1

User: 2027-04-20
so 3
keep 3
why 2
support 2
do 1

User: 2027-05-20
none, 7
im 1
genuinely 1
happy 1
you! 1

User: 2027-06-20
none, 3
so 2
this. 2
cant 2
great 2

User: 2027-07-20
spreading 5
keep 4
truly 3
this 3
just 3

User: 2027-08-20
none, 4
just 2
posts 1
always 1
bring 1

User: 2027-09-20
none, 7
this 1
so 1
disappointing. 1
i 1

User: 2027-10-20
keep 2
just 2
support 1
means 1
everything. 1

User: 2030-01-10
keep 3
none, 3
support 2
means 2
kindness 1

User: 2030-02-10
none, 6
have 1
such 1
warm 1
loving 1

User: 2030-03-10
keep 4
none, 3
spreading 2
support 2
positivity! 1

User: 2030-04-10
this 3
keep 3
truly 1
heartwarming. 1
spreading 1

User: 2030-05-10
this 3
keep 3
really 2
sad. 2
disappointing., 2

User: 2030-06-10
none, 4
truly 2
kindness 2
keep 2
up!, 2

User: 2030-07-10
keep 3
just 2
negative 2
influence. 2
stop., 2

User: 2030-08-10
none, 4
this 1
utterly 1
disappointing. 1
should 1

User: 2030-09-10
none, 7
support 1
means 1
everything. 1
keep 1

User: 2030-10-10
none, 5
i 1
cant 1
believe 1
how 1

User: 2031-01-10
keep 4
this 3
truly 2
have 2
spreading 2

User: 2031-02-10
keep 5
truly 3
kindness 2
are 2
positivity 1

User: 2031-03-10
none, 5
creativity 1
truly 1
inspiring!, 1
just 1

User: 2031-04-10
none, 7
support 1
means 1
everything. 1
keep 1

User: 2031-05-10
this 4
none, 4
truly 2
heartwarming. 2
keep 2

User: 2031-06-10
none, 5
creativity 2
truly 2
innovation 1
are 1

User: 2031-07-10
keep 3
spreading 3
stop 2
so 2
an 1

User: 2031-08-10
none, 5
disgrace. 1
shameful., 1
stop 1
spreading 1

User: 2031-09-10
keep 3
up!, 2
this 2
support 1
kindness 1

User: 2032-03-10
none, 5
just 1
downer. 1
cant 1
stand 1

User: 2032-04-10
keep 3
this 2
kindness 2
up!, 2
i 2

User: 2032-05-10
none, 3
keep 2
such 2
words 1
encouragement 1

User: 2032-06-10
none, 6
keep 2
unwavering 1
support 1
means 1

User: 2032-07-10
none, 7
support 1
invaluable. 1
keep 1
shining!, 1

User: 2032-08-10
none, 7
positivity 1
needed. 1
keep 1
spreading 1

User: 2032-09-10
none, 5
keep 2
empathy 1
kindness 1
are 1

User: 2032-10-10
just 2
why 2
so 2
keep 2
this 2

User: 2032-11-10
truly 5
keep 5
up!, 4
words 3
encouragement 3

User: 2032-12-10
keep 3
so 3
empathy 2
kindness 2
are 2

User: 2033-01-10
this 3
truly 3
heartwarming. 2
keep 2
spreading 2

User: 2033-02-10
truly 3
keep 3
this 2
just 2
heartwarming. 1

User: 2033-03-10
so 3
cant 3
are 2
always 2
see 2

User: 2033-04-10
keep 4
truly 3
support 2
spreading 2
just 1

User: 2033-05-10
none, 3
keep 2
spreading 2
have 1
such 1

User: 2033-06-10
none, 7
have 1
such 1
warm 1
loving 1

User: 2033-07-10
none, 4
keep 3
kindness 2
up!, 2
truly 2

User: 2033-08-10
none, 4
cant 2
content 1
brightens 1
my 1

User: 2034-01-10
creativity 2
truly 2
inspiring!, 2
an 1
inspiration 1

User: 2034-02-10
keep 3
none, 3
this 2
heartwarming. 2
truly 2

User: 2034-03-10
none, 4
keep 2
just 1
downer. 1
cant 1

User: 2034-04-10
keep 4
this 3
support 2
none, 2
invaluable. 1

User: 2034-05-10
so 4
this 2
stop 2
support 1
means 1

User: 2034-06-10
none, 7
positivity 1
needed. 1
keep 1
up!, 1

User: 2034-07-10
none, 4
so 2
positivity 1
needed. 1
keep 1

User: 2034-08-10
keep 3
spreading 2
truly 2
this 2
none, 2

User: 2034-09-10
keep 5
support 2
means 2
truly 2
have 2

User: 2034-10-10
none, 5
support 1
means 1
everything 1
me!, 1

User: 2034-11-10
none, 6
just 1
negative 1
presence. 1
go 1

User: 2034-12-10
keep 5
truly 3
appreciated. 3
up!, 3
negative 2

/var/folders/gc/4fdvc12d49v5064nxvddsyj00000gn/T/ipykernel_70724/4280764203.py:7: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  instaClean = instagram_information.applymap(lambda x: re.sub(r'[\[\]\(\)"\']', '', str(x)))
/var/folders/gc/4fdvc12d49v5064nxvddsyj00000gn/T/ipykernel_70724/4280764203.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  instaClean = instaClean.applymap(lambda x: x.lower())
/var/folders/gc/4fdvc12d49v5064nxvddsyj00000gn/T/ipykernel_70724/4280764203.py:16: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  instaClean = instaClean.applymap(lambda x: ' '.join([word for word in x.split() if word not in filler_words]))